### PR TITLE
show track lengths on album tracks

### LINKED ISSUE #28: display track lengths on album pages
@nagapampa talk to @jjg about where the metadata is

### PR DESCRIPTION
**Pull request by mbrakken**
Show track legnths if we have the data, otherwise show "0:00".

Cases without data are still pending processing.

Closes #28, although we may need to revisit styling on tracklists. I know there's current work afoot for mobile already, #64, so deferring style updates to that issue.

### CODE REVIEW

**Comment by mbrakken** [comment]
Reassigned to @nagapampa for review, merge, deploy.

**Comment by nagapampa** [comment]
FYI - This is getting tight in the mobile view

**Comment by mbrakken** [comment]
Yeah, and the fact that it's a @$#! table doesn't help. I may refactor into
a OL, and then we can be more flexible about positioning contents for
different contexts.

**Comment by prestonaustin** [comment]
Once it is all functionally there, move any aesthetics to a new ticket. We can wrap or truncate stuff here to make that work. Not saying the aesthetics aren't important, cuz they are, but don't want to keep that in this ticket or block going live over those improvements.

**Comment by mbrakken** [comment]
Yupyup

**Pull request merged**
