### PR TITLE
added promise to get banner image from git

### PR DESCRIPTION
**Pull request by nagapampa**
Banner content no longer hard coded but retrieved from GitHub directly.

### CODE REVIEW

**Comment by mbrakken** [comment]
I'm pretty sure that before this goes out, will need to disable fingerprinting for the images it uses: http://www.ember-cli.com/user-guide/#fingerprinting-and-cdn-urls

If you look at the urls in the actual deployed app, they look like this: https://capitalcityrecords.ca/assets/banner1-cd0135bd735dd691b73298cc5dfcec8a.png

The characters at the end are the fingerprinting, which is to help ensure integrity of the files delivered if they were being served out of a CDN.

Since we're not serving images out of a CDN, we could either disable fingerprinting entirely or move the images into a /banners/ folder and disable fingerprinting on anything in that folder, probably by adding
```
fingerprint: {
    exclude: ['banners/']
}
```
to ember-cli-build.js

**Comment by nagapampa** [comment]
@mbrakken This has been added as well as a new /banner DIR in the master branch in the new /content DIR.  I don't think the config change can be fully tested outside of a production environment...  works locally fine.

**Comment by mbrakken** [comment]
Thanks. I'll take a look at this later tonight.

**Comment by mbrakken** [comment]
Ok. I just touched it up a bit and added the banner for submissions. Updated the JSON on github, too. I believe this can go out.

Small note: after you changed to loading the images directly out of github instead of from the app server, the fingerprint config stuff is no longer pertinent.

Feel free to merge and deploy.

**Pull request closed without merging**
